### GET request with a header
GET http://localhost:3000/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoidXNlcklkXyIsImlhdCI6MTYwMzYzNjQ3MCwiZXhwIjoxNjAzNjM2NzcwfQ.q3d59DNjaopgDDgy4K70NB0KTHMDVx0R9NJoBiurgKI
